[package]
name = "pdf-excel-lambda"
version = "0.1.0"
edition = "2024"

[dependencies]
pdfium-render = "0.8.37"
serde = { version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
thiserror = "2.0.17"
